name: "CI / CD"

on:
  push:
    branches: [ "main", "feature/*", "bugfix/*" ]

  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  VCPKG_BINARY_SOURCES: "clear;files,${{ github.workspace }}/.vcpkg,readwrite"

jobs:
  strings:
    runs-on: ubuntu-latest
    outputs:
      build-version: ${{ steps.strings.outputs.build-version }}
    steps:
      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          COMMIT_HASH=${{ github.sha }}
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "${{ github.event.repository.default_branch }}" ] && VERSION=latest
          VERSION="$VERSION+sha.${COMMIT_HASH:0:8}"
          echo VERSION=$VERSION
          echo "build-version=${VERSION}" >> "$GITHUB_OUTPUT"

  build-test-package:
    needs: [ strings ]
    runs-on: ubuntu-latest
    steps:
      - name: Dependencies
        run: |
          sudo apt update
          sudo apt install --yes \
            autoconf \
            autoconf-archive \
            automake \
            libtool \
            libltdl-dev

      - uses: actions/checkout@v5

      - uses: lukka/get-cmake@latest

      - uses: lukka/run-vcpkg@v11.6

      - uses: actions/cache/restore@v5
        id: vcpkg-cache
        with:
          path: ${{ github.workspace }}/.vcpkg
          key: vcpkg-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json') }}
          restore-keys: vcpkg-


      - name: Configure CMake
        run: cmake --preset ci

      - uses: actions/cache/save@v5
        if: ( ! cancelled() )
        with:
          path: ${{ github.workspace }}/.vcpkg
          key: ${{ steps.cache-vcpkg.outputs.cache-primary-key }}

      - name: Build
        run: cmake --build build/ci --config Debug

      - name: Test
        run: ctest --preset ci

      - name: Package
        run: cpack --preset ci -R "${{ needs.strings.outputs.build-version }}"

      - uses: actions/upload-artifact@v4
        with:
          name: nel-tools-usd-${{ needs.strings.outputs.build-version }}
          path: build/ci/learning-vcpkg-*
          if-no-files-found: error
