name: "CI / CD"

on:
  push:
    branches: [ "main", "feature/*", "bugfix/*" ]

  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  VCPKG_BINARY_SOURCES: "clear;files,${{ github.workspace }}/.vcpkg,readwrite"

jobs:
  strings:
    runs-on: ubuntu-latest
    outputs:
      build-version: ${{ steps.strings.outputs.build-version }}
      docker-group: ${{ steps.strings.outputs.docker-group }}
      docker-image-version: ${{ steps.strings.outputs.docker-image-version }}
      docker-image-tag: ${{ steps.strings.outputs.docker-image-tag }}
    steps:
      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          COMMIT_HASH=${{ github.sha }}
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "${{ github.event.repository.default_branch }}" ] && VERSION=latest
          DOCKER_GROUP=$(echo "ghcr.io/${{ github.repository_owner }}" | tr '[A-Z]' '[a-z]')
          echo "build-version=${VERSION}+sha.${COMMIT_HASH:0:8}" >> "$GITHUB_OUTPUT"
          echo "docker-group=${DOCKER_GROUP}" >> "$GITHUB_OUTPUT"
          echo "docker-image-version=${VERSION}" >> "$GITHUB_OUTPUT"
          echo "docker-image-tag=${DOCKER_GROUP}/nel-tools-usd:${VERSION}" >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"

  build:
    needs: [ strings ]
    runs-on: ubuntu-latest
    outputs:
      artifact-id: ${{ steps.upload-artifact.outputs.artifact-id }}
    steps:
      - name: Dependencies
        run: |
          sudo apt update
          sudo apt install --yes \
            autoconf \
            autoconf-archive \
            automake \
            libltdl-dev \
            libtool \
            linux-libc-dev \
            pkg-config

      - uses: actions/checkout@v7

      - uses: lukka/get-cmake@latest

      - uses: lukka/run-vcpkg@v11.6

      - uses: actions/cache/restore@v6
        id: vcpkg-cache
        with:
          path: ${{ github.workspace }}/.vcpkg
          key: vcpkg-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json') }}
          restore-keys: vcpkg-


      - name: Configure CMake
        run: cmake --preset ci

      - uses: actions/cache/save@v6
        if: ( ! cancelled() && steps.vcpkg-cache.outputs.cache-hit != 'true')
        with:
          path: ${{ github.workspace }}/.vcpkg
          key: ${{ steps.vcpkg-cache.outputs.cache-primary-key }}

      - name: Build
        run: cmake --build build/ci --config Debug

      - name: Test
        run: ctest --preset ci

      - uses: actions/upload-artifact@v7
        if: ( !cancelled() )
        with:
          name: test-results
          if-no-files-found: error
          path: build/reports/*.xml
          retention-days: 1

      - name: Package
        run: cpack --preset ci -R "${{ needs.strings.outputs.build-version }}"

      - name: Build Docker image
        run: |
          docker build build/ci --file cmake/Dockerfile --tag "${{ needs.strings.outputs.docker-image-tag }}"
          docker save --output=build/ci/nel-tools-usd-${{ needs.strings.outputs.docker-image-version }}-docker.tar "${{ needs.strings.outputs.docker-image-tag }}"

      - uses: actions/upload-artifact@v7
        id: upload-artifact
        with:
          name: nel-tools-usd-${{ needs.strings.outputs.build-version }}
          path: build/ci/nel-tools-usd-*
          if-no-files-found: error

  publish:
    needs: [ strings, build ]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch ) }}
    steps:
      - uses: actions/download-artifact@v8
        with:
          artifact-ids: ${{ needs.build.outputs.artifact-id }}
          merge-multiple: true
          path: build

      - run: find build

      - run: find build -type f -iname *-docker.tar -exec docker load --input {} \;

      - name: Push image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
          docker images
          docker push "${{ needs.strings.outputs.docker-image-tag }}"
